if: branch =~ ^master$|^development$
group: stable
dist: xenial
os: linux
sudo: required
language: php
php: 7.2

before_script: |-
  phpenv config-rm xdebug.ini

install:
  - composer install --prefer-dist --optimize-autoloader --quiet