if: branch =~ ^master$|^development$
group: stable
dist: xenial
os: linux
sudo: required
language: php
php: 7.2

before_script: |-
  sudo add-apt-repository -y ppa:ondrej/php
  sudo apt-get update
  sudo apt-get install -y php7.2-common php7.2-cli php7.2-fpm php7.2-dev
  export SWOOLE_EXT_VERSION=4.4.7
  yes"" | pecl install swoole-${SWOOLE_EXT_VERSION}