if: branch =~ ^master$|^development$
group: stable
dist: xenial
os: linux
sudo: required
language: php
php: 7.2
install: composer install --no-ansi --no-interaction --no-progress --prefer-dist
script: vendor/bin/phpunit