if: branch =~ ^master$|^development$
group: stable
dist: xenial
os: linux
sudo: required
language: php
php: 7.2

before_script:
  - composer install

script: ./vendor/bin/phpunit -c phpunit.xml


notifications:
  email: false